---
app:
  title: Backstage Dev Portal
  baseUrl: http://localhost:3000
  support:
    url: https://github.com/backstage/backstage/issues # Used by common ErrorPage
    items: # Used by common SupportButton component
      - title: Issues
        icon: github
        links:
          - url: https://github.com/backstage/backstage/issues
            title: GitHub Issues
      - title: Discord Chatroom
        icon: chat
        links:
          - url: https://discord.gg/MUpMjP2
            title: '#backstage'

organization:
  name:
    
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:7007
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      # https://node-postgres.com/features/ssl
      # ssl: require # see https://www.postgresql.org/docs/current/libpq-ssl.html
      # Table 33.1. SSL Mode Descriptions (e.g. require)
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt
  cache:
    store: memory
    # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir
  reading:
    allow:
      - host: '*.tw.com'

integrations:
  bitbucket:
    - host: bitbucket.org
      username: ${BITBUCKET_USERNAME}
      appPassword: ${BITBUCKET_APP_PASSWORD}

proxy:
  '/circleci/api':
    target: https://circleci.com/api/v1.1
    headers:
      Circle-Token: ${CIRCLECI_AUTH_TOKEN}

  # Environmental variable: SONARQUBE_TOKEN
  # Fetch the sonar-auth-token from https://sonarcloud.io/account/security/
  '/sonarqube':
    target: https://sonar.tw.com/api
    allowedMethods: ['GET']
    auth: ${SONARQUBE_TOKEN}

  '/lighthouse':
    target: https://api.nonprod-internal.twcloud.com/productcore/lighthouse-audit-service
    allowedMethods: ['GET', 'POST', 'PUT']

sonarQube:
  baseUrl: https://sonar.tw.com/

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: {}

scaffolder:
  bitbucket:
    api:
      host: https://bitbucket.org
      username: ${BITBUCKET_USERNAME}
      token: ${BITBUCKET_APP_PASSWORD}

techdocs:
  builder: 'local'  # Alternatives - 'external'

lighthouse:
  baseUrl: ${LIGHTHOUSE_URL}

techradar:
  radarDataUrl: "./starterkits/backstage-techradar/radar-data.json"
  username: ${BITBUCKET_USERNAME}
  password: ${BITBUCKET_APP_PASSWORD}


catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Template]
  locations:
    #####
    # Below are the Starter Kit Templates
    #####
    # Documentation Template
    - type: path
      target: ./starterkits/starterkit-docs/src/master/template.yaml
      rules:
        - allow: [Template]

    # Node Backend Template
    - type: path
      target: ./starterkits/template-me-nodejs/src/master/template.yaml
      rules:
        - allow: [Template]

    # Java starterkit from test-skeleton
    - type: path
      target: ./starterkits/test-skeleton/src/master/template.yaml
      rules:
        - allow: [Template]

    # Backstage template for local setup
    - type: path
      target: ./starterkits/local-setup/src/master/template.yaml
      rules:
        - allow: [Template]

    # React Starterkit Template
    - type: path
      target: ./starterkits/template-me-nextjs/src/master/template.yaml
      rules:
        - allow: [Template]


    #####
    # Below are the Domain, System configurations
    ####

    # Corporate Services Domain
    - type: url
      target: https://bitbucket.org/wwgrainger/backstage_heirarchy/src/master/domains/corporate-services/catalog-info.yaml
      rules:
        - allow: [Domain]

    # Corp services sub-domains
    - type: url
      target: https://bitbucket.org/wwgrainger/backstage_heirarchy/src/master/domains/corporate-services/sub-domains/EHS/catalog-info.yaml
      rules:
        - allow: [System]
