apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  AZURE_TECHDOCS_STORAGE_KEY: ${AZURE_TECHDOCS_STORAGE_KEY}
## we are not using this file for secrets
## we have created secrets directly in azure pipeline