#Note this will only need to be applied once in your K8 instance
#This is here to help with new installs
#Do not check this into a repo with secrets

# You can use K8 secrets or apply then from the deployment pipeline
# varabiles can be used in the app-config.yaml from either type

apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_SERVICE_HOST:
  POSTGRES_SERVICE_PORT:
  BACKEND_SECRET: #this is used to pass a secret between plugins and backstage services.  Expected to be a string.
  #If using Azure for techdocs
  AZURE_TECHDOCS_BUCKET_NAME:
  AZURE_TECHDOCS_ACCOUNT_NAME:
  AZURE_TECHDOCS_STORAGE_KEY:
  #If you are using AWS for Techdocs
  AWS_ACCOUNT_ID:
  AWS_TECHDOCS_BUCKET_NAME:
  AWS_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: