# on a review from someone in the reviewers group, remove the awaiting-review label and add the awaiting-author label
name: Automate review labels - scheduled
on:
  schedule:
    - cron: '* * * * *'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          application_private_key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          organization: backstage

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install codeowners

      - uses: actions/github-script@v5
        id: fix-labels
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            const script = require('./scripts/goalie-labels.js')
            await script({github, context, core})
