name: Automate staleness
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # run every 10 minutes as it also removes labels.

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-issue-stale: 60
          days-before-issue-close: 7
          exempt-issue-labels: 'pinned,security,plugin,help wanted,good first issue,rfc,will-fix'
          stale-issue-label: stale
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not had
            recent activity from the author. It will be closed if no further activity occurs.
            If you are the author and the PR has been closed, feel free to re-open the PR and continue the contribution!
          days-before-pr-stale: 7
          days-before-pr-close: 5
          exempt-pr-labels: reviewer-approved,awaiting-review,will-fix
          stale-pr-label: stale
          operations-per-run: 100
