name: Sync Version Packages PR
on:
  push:
    branches:
      - master

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Create Release Pull Request
        uses: backstage/changesets-action@v2
        with:
          # Calls out to `changeset version`, but also runs prettier
          version: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          HUSKY: '0'
