# Building on windows is really slow, so this workflow is separate from e2e.yml and only builds on changes
# to the cli itself. They're more likely to introduce issues on windows, compared to changes to core and yarn.lock.

name: E2E Test Windows
on:
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]
        node-version: [14.x, 16.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      # In order to have the create-app template function as if it was downloaded from NPM
      # we need to make sure we checkout files with LF line endings only
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: setup chrome
        uses: browser-actions/setup-chrome@latest
      - name: yarn install
        run: yarn install --frozen-lockfile

      - run: yarn tsc
      - run: yarn backstage-cli repo build
      - name: run E2E test
        run: yarn e2e-test run
        env:
          DEBUG: zombie
